# ==========================================
# BUSINESS SALES PERFORMANCE ANALYTICS
# Future Interns - Task 1
# ==========================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Create folders if not exist
os.makedirs("images", exist_ok=True)

# ------------------------------------------
# LOAD DATASET
# ------------------------------------------

df = pd.read_csv("data/superstore_sales.csv", encoding='latin1')

print("\nDATASET LOADED SUCCESSFULLY\n")

# ------------------------------------------
# BASIC INFORMATION
# ------------------------------------------

print("FIRST 5 ROWS")
print(df.head())

print("\nDATASET INFO")
print(df.info())

print("\nMISSING VALUES")
print(df.isnull().sum())

# ------------------------------------------
# DATA CLEANING
# ------------------------------------------

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Convert Order Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Create Month-Year column
df['Month-Year'] = df['Order Date'].dt.to_period('M')

print("\nDATA CLEANING COMPLETED")

# ------------------------------------------
# KPI CALCULATIONS
# ------------------------------------------

total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
total_orders = df['Order ID'].nunique()
average_order_value = total_sales / total_orders

print("\n========== KPI SUMMARY ==========")
print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Total Orders: {total_orders}")
print(f"Average Order Value: ${average_order_value:,.2f}")

# ------------------------------------------
# MONTHLY SALES TREND
# ------------------------------------------

monthly_sales = df.groupby('Month-Year')['Sales'].sum()

plt.figure(figsize=(12,6))
monthly_sales.plot(marker='o')

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.xticks(rotation=45)
plt.grid(True)

plt.savefig("images/monthly_sales.png")
plt.close()

print("\nMonthly Sales Chart Saved")

# ------------------------------------------
# REGIONAL SALES ANALYSIS
# ------------------------------------------

region_sales = df.groupby('Region')['Sales'].sum().sort_values()

plt.figure(figsize=(10,6))

region_sales.plot(
    kind='bar',
)

plt.title("Regional Sales Performance")
plt.xlabel("Region")
plt.ylabel("Sales")

plt.xticks(rotation=0)

plt.savefig("images/regional_sales.png")
plt.close()

print("Regional Sales Chart Saved")

# ------------------------------------------
# TOP 10 PRODUCTS
# ------------------------------------------

top_products = (
    df.groupby('Product Name')['Sales']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(12,7))

top_products.plot(kind='barh')

plt.title("Top 10 Products by Sales")
plt.xlabel("Sales")
plt.ylabel("Product")

plt.savefig("images/top_products.png")
plt.close()

print("Top Products Chart Saved")

# ------------------------------------------
# CATEGORY PROFIT ANALYSIS
# ------------------------------------------

category_profit = df.groupby('Category')['Profit'].sum()

plt.figure(figsize=(8,6))

category_profit.plot(kind='bar')

plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Profit")

plt.xticks(rotation=0)

plt.savefig("images/category_profit.png")
plt.close()

print("Category Profit Chart Saved")

# ------------------------------------------
# SALES VS PROFIT SCATTERPLOT
# ------------------------------------------

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df,
    x='Sales',
    y='Profit',
    hue='Category'
)

plt.title("Sales vs Profit")

plt.savefig("images/sales_vs_profit.png")
plt.close()

print("Sales vs Profit Chart Saved")

# ------------------------------------------
# TOP CATEGORIES
# ------------------------------------------

top_categories = (
    df.groupby('Category')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print("\n========== TOP CATEGORIES ==========")
print(top_categories)

# ------------------------------------------
# MOST PROFITABLE REGION
# ------------------------------------------

region_profit = df.groupby('Region')['Profit'].sum()

print("\n========== REGION PROFITS ==========")
print(region_profit)

# ------------------------------------------
# BUSINESS INSIGHTS
# ------------------------------------------

print("\n========== BUSINESS INSIGHTS ==========")

best_category = top_categories.idxmax()
best_region = region_profit.idxmax()

print(f"1. Highest revenue generated by category: {best_category}")
print(f"2. Most profitable region: {best_region}")

loss_products = df[df['Profit'] < 0]

print(f"3. Number of loss-making products: {len(loss_products)}")

print("4. Sales trends analyzed successfully")
print("5. Dashboard-ready visualizations created")

# ------------------------------------------
# EXPORT SUMMARY REPORT
# ------------------------------------------

summary = pd.DataFrame({
    'Metric': [
        'Total Sales',
        'Total Profit',
        'Total Orders',
        'Average Order Value'
    ],
    'Value': [
        total_sales,
        total_profit,
        total_orders,
        average_order_value
    ]
})

summary.to_csv("reports/business_summary.csv", index=False)

print("\nSummary Report Exported")

# ------------------------------------------
# COMPLETION MESSAGE
# ------------------------------------------

print("\n====================================")
print("TASK 1 COMPLETED SUCCESSFULLY")
print("All charts saved in images folder")
print("====================================")